options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages(c("readr","ggplot2","tidyr", "skimr", "Rtsne"))
install.packages("tidyverse", dependencies = TRUE)
install.packages("rmarkdown", dependencies = TRUE)
install.packages("IRkernel", dependencies = TRUE)
install.packages("caret", dependencies = TRUE)
install.packages("glmnet", dependencies = TRUE)
install.packages("httr", dependencies = TRUE)
install.packages("jsonlite", dependencies = TRUE)
install.packages("tokenizers", dependencies = TRUE)
install.packages("stringr", dependencies = TRUE)
install.packages("R6", dependencies = TRUE)
install.packages("digest", dependencies = TRUE)
install.packages("viridis", dependencies = TRUE)

IRkernel::installspec(user = FALSE)
